trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - Infrastructure/*

pool:
  name: LocalPool

variables:
  resourceGroup: uan-rg-rts
  location: eastus
  subscription: 0cd1b4a4-98c0-48dd-900e-532a1f9a345c

stages:
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: AzureCLI@2
      displayName: Create Resource Group
      inputs:
        azureSubscription: azure-default
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: az group create --location $(location) --name $(resourceGroup) --subscription $(subscription)
    - task: AzureResourceGroupDeployment@2
      displayName: Create Release Management App Infrastructure
      inputs:
        azureSubscription: azure-default
        resourceGroupName: $(resourceGroup)
        action: 'Create Or Update Resource Group'
        location: $(location)
        templateLocation: 'Linked artifact'
        deploymentMode: Incremental
        csmFile: '$(Build.SourcesDirectory)/Infrastructure/ARM/releaseManagementApp.json'
        csmParametersFile: '$(Build.SourcesDirectory)/Infrastructure/ARM/releaseManagementApp.parameters.json'