trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - Infrastructure/*

variables:
  resourceGroup: uan-rg-rts
  resourceGroupShared: uan-rg-rts-shared
  location: eastus
  subscription: 0cd1b4a4-98c0-48dd-900e-532a1f9a345c
  vmImageName: 'ubuntu-latest'

pool:
    vmImage: $(vmImageName)

stages:
- stage: Deploy
  jobs:
  - job: DeployFunctionAppInfra
    displayName: Deploy Release Manager Function App Infrastructure
    steps:
    
    - task: AzureCLI@2
      displayName: Create Resource Group
      inputs:
        azureSubscription: azure-default
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: az group create --location $(location) --name $(resourceGroup) --subscription $(subscription)

    - task: AzureResourceGroupDeployment@2
      displayName: Create Release Management Function App Infrastructure
      inputs:
        azureSubscription: azure-default
        resourceGroupName: $(resourceGroup)
        action: 'Create Or Update Resource Group'
        location: $(location)
        templateLocation: 'Linked artifact'
        deploymentMode: Incremental
        csmFile: '$(Build.SourcesDirectory)/Infrastructure/ARM/releaseManagerFunctionApp.json'
        csmParametersFile: '$(Build.SourcesDirectory)/Infrastructure/ARM/releaseManagerFunctionApp.parameters.json'

  - job: DeployWebAppInfra
    displayName: Deploy Release Manager Web App
    dependsOn: DeployFunctionAppInfra
    steps:
    
    - task: AzureCLI@2
      displayName: Create Resource Group
      inputs:
        azureSubscription: azure-default
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: az group create --location $(location) --name $(resourceGroupShared) --subscription $(subscription)

    - task: AzureResourceGroupDeployment@2
      displayName: Create Release Management Web App Infrastructure
      inputs:
        azureSubscription: azure-default
        resourceGroupName: $(resourceGroupShared)
        action: 'Create Or Update Resource Group'
        location: $(location)
        templateLocation: 'Linked artifact'
        deploymentMode: Incremental
        csmFile: '$(Build.SourcesDirectory)/Infrastructure/ARM/releaseManagerWebApp.json'
        csmParametersFile: '$(Build.SourcesDirectory)/Infrastructure/ARM/releaseManagerWebApp.parameters.json'